package com.iHotel.view;

import javax.swing.*;

/**
 * @author Eugenio
 */
public class VFrameCreaPrenotazioneHome extends JFrame {

	/**
	 * Creates new form VFrameCreaPrenotazioneHome
	 */
	public VFrameCreaPrenotazioneHome() {
		// TODO - implement VFrameCreaPrenotazioneHome.VFrameCreaPrenotazioneHome
		throw new UnsupportedOperationException();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {
		// TODO - implement VFrameCreaPrenotazioneHome.initComponents
		throw new UnsupportedOperationException();
	}

	/**
	 * 
	 * @param args the command line arguments
	 */
	public static void main(java.lang.String[] args) {
		// TODO - implement VFrameCreaPrenotazioneHome.main
		throw new UnsupportedOperationException();
	}

}